general {
    lock_cmd = pidof swaylock || /usr/bin/swaylock    # avoid starting multiple swaylock instances.
    before_sleep_cmd = loginctl lock-session    # lock before suspend.
    after_sleep_cmd = ~/scripts/backlight_save_restore.sh restore
}
listener {
    timeout = 200
    on-timeout = ~/scripts/backlight_save_restore.sh percent 33 900
    on-resume = ~/scripts/backlight_save_restore.sh restore
}
listener {
    timeout = 240
    on-timeout = ~/scripts/backlight_save_restore.sh set 0 3000
    on-resume = ~/scripts/backlight_save_restore.sh restore  
}
listener {
    timeout = 243                                         
    on-timeout = niri msg action power-off-monitors
}
listener {
    timeout = 260
    on-timeout = swaylock
}
